#!/usr/bin/env python3
"""
mirror_docs.py — gather every Markdown doc in the repo into one easy-to-read place.
================================================================================
Copies every ``.md`` file in the repository, BYTE-FOR-BYTE, into
``scripts/support/knowledge/_mirror/`` so all documentation can be browsed in a
single folder. Originals are LEFT IN PLACE — this is a mirror, not a move.

Copies land in a ``_mirror/`` subfolder (kept separate from the hand-written guides
in ``knowledge/`` so the mirror can never clobber them — e.g. the repo-root
``README.md`` would otherwise collide with the knowledge index). Each copy is named
by its source path with separators flattened to ``__`` so docs from different folders
never collide, e.g.::

    scripts/managers/services/plex/DESIGN_personal_playlists.md
        ->  _mirror/scripts__managers__services__plex__DESIGN_personal_playlists.md

A generated ``_mirror/INDEX.md`` maps every copy back to its source path.

Re-runnable: each run rebuilds ``_mirror/`` from scratch, so copies are always in
sync with the originals and stale ones (moved/deleted sources) disappear automatically.

Usage::

    python scripts/support/tools/mirror_docs.py            # rebuild the mirror
    python scripts/support/tools/mirror_docs.py --dry-run  # show what it would do

The generated ``_mirror/`` folder is a derived artifact — gitignore it if you'd
rather not commit the mirror, and just keep this tool + the curated guides.
"""
from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path

# scripts/support/tools/mirror_docs.py -> parents[3] == repo root
REPO_ROOT = Path(__file__).resolve().parents[3]
KNOWLEDGE_DIR = REPO_ROOT / "scripts" / "support" / "knowledge"
MIRROR_DIR = KNOWLEDGE_DIR / "_mirror"

# Directories never worth scanning (VCS / build / deps / caches). The knowledge dir
# is excluded so the mirror never re-mirrors its own copies or the curated guides.
_SKIP_DIRS = {
    ".git", ".hg", ".svn", ".venv", "venv", "env", "node_modules", "__pycache__",
    ".mypy_cache", ".pytest_cache", ".ruff_cache", ".tox", "build", "dist",
    ".idea", ".vscode", "site-packages", ".eggs", "knowledge",
}


def _encode(rel: Path) -> str:
    """A source path relative to the repo -> a collision-free flat filename."""
    return "__".join(rel.parts)


def iter_markdown():
    """Yield every ``.md`` path under the repo, skipping ``_SKIP_DIRS`` (incl. the
    knowledge dir). Skip-dirs are pruned in place so we never descend into them."""
    for dirpath, dirnames, filenames in os.walk(REPO_ROOT):
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS]
        for name in filenames:
            if name.lower().endswith(".md"):
                yield Path(dirpath) / name


def mirror(dry_run: bool = False) -> int:
    """Rebuild the mirror; return the number of docs mirrored."""
    pairs = []
    for src in sorted(iter_markdown(), key=lambda p: p.as_posix().lower()):
        rel = src.relative_to(REPO_ROOT)
        pairs.append((rel, _encode(rel)))

    verb = "[dry-run] would mirror" if dry_run else "mirroring"
    print(f"mirror_docs: {verb} {len(pairs)} markdown doc(s) -> "
          f"{MIRROR_DIR.relative_to(REPO_ROOT).as_posix()}/")
    if dry_run:
        for rel, name in pairs:
            print(f"  + {rel.as_posix()}  ->  {name}")
        return len(pairs)

    if MIRROR_DIR.exists():
        shutil.rmtree(MIRROR_DIR)                          # full rebuild = automatic prune
    MIRROR_DIR.mkdir(parents=True, exist_ok=True)
    for rel, name in pairs:
        shutil.copyfile(REPO_ROOT / rel, MIRROR_DIR / name)   # copyfile = byte-for-byte
    _write_index(pairs)
    print(f"mirror_docs: wrote {len(pairs)} copy(ies) + INDEX.md")
    return len(pairs)


def _write_index(pairs) -> None:
    """A human index mapping each mirrored copy back to its source path."""
    lines = [
        "# Mirrored documentation",
        "",
        "Byte-for-byte copies of every `.md` in the repo, generated by "
        "`scripts/support/tools/mirror_docs.py`. Originals remain in place; edit those, not these.",
        "",
        "| Document | Source path |",
        "| --- | --- |",
    ]
    for rel, name in pairs:
        lines.append(f"| [{name}]({name}) | `{rel.as_posix()}` |")
    (MIRROR_DIR / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Mirror every repo .md into scripts/support/knowledge/_mirror/.")
    ap.add_argument("--dry-run", action="store_true", help="show what would change without writing")
    args = ap.parse_args(argv)
    mirror(dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
