# ✅ Optimized Cache Key Registry
# Organizes all service cache keys using hierarchical, standardized naming.

class CacheKeyPaths:
    class sonarr:
        LIBRARY = "sonarr/<instance>/library"
        LIBRARY_LAST_UPDATED = "sonarr/<instance>/library/last_updated"
        ALL_EPISODES = "sonarr/<instance>/episodes/all"
        EPISODE_MONITORING = "sonarr/<instance>/episodes/monitoring"
        FUTURE_EPISODES = "sonarr/<instance>/episodes/future"
        EPISODES_BY_SERIES = "sonarr/<instance>/episodes/by_series"
        EPISODE_PROFILES = "sonarr/<instance>/profiles"
        SONARR_LIBRARY = "sonarr/<instance>/library"
        METADATA = "sonarr/<instance>/metadata"
        INSTANCE_MAPPINGS = "sonarr/mappings"
        SPACE_ESTIMATES = "sonarr/<instance>/storage/space_estimates"
        MONITORED_SYNC = "sonarr/<instance>/sync/monitored"
        QUALITY_PROFILES = "sonarr/<instance>/quality/profiles"
        TAGS = "sonarr/<instance>/tags"
        CUSTOM_FORMATS = "sonarr/<instance>/custom_formats"
        WATCHED_SHOWS = "tautulli/<instance>/watched/shows"
        WATCH_COUNTS_SERIES = "tautulli/<instance>/watched/counts"
        LAST_PLAYED_SERIES = "tautulli/<instance>/watched/last_played"
        REWATCH_CANDIDATES = "tautulli/<instance>/watched/rewatch"
        SERIES_MISSING_FROM_SONARR = "tautulli/<instance>/crosscheck/missing_in_sonarr"

    class radarr:
        RADARR_LIBRARY = "radarr/<instance>/library"
        ALL_MOVIES = "radarr/<instance>/movies/all"
        FUTURE_MOVIES = "radarr/<instance>/movies/future"
        MONITORED_MOVIES = "radarr/<instance>/movies/monitored"
        USER_RATINGS_MOVIES = "radarr/<instance>/movies/ratings"
        METADATA = "radarr/<instance>/metadata"
        INSTANCE_MAPPINGS = "radarr/mappings"
        SPACE_ESTIMATES = "radarr/<instance>/storage/space_estimates"
        MONITORED_SYNC = "radarr/<instance>/sync/monitored"
        QUALITY_PROFILES = "radarr/<instance>/quality/profiles"
        TAGS = "radarr/<instance>/tags"
        CUSTOM_FORMATS = "radarr/<instance>/custom_formats"


    class trakt:
        WATCH_HISTORY = "trakt/<user>/watch/history"
        WATCHLIST = "trakt/<user>/watchlist"
        RECOMMENDATIONS = "trakt/<user>/recommendations"
        PROCESSED = "trakt/<user>/processed"
        USER_RATINGS_SHOWS = "trakt/<user>/ratings/shows"
        USER_RATINGS_EPISODES = "trakt/<user>/ratings/episodes"
        RATINGS_ALL = "trakt/<user>/ratings/all"
        USER_RATINGS_MOVIES = "trakt/<user>/ratings/movies"
        USER_RATINGS = "trakt/<user>/ratings"
        USER_LISTS = "trakt/<user>/lists"
        LIST_ITEMS = "trakt/<user>/lists/default/items"
        HISTORY = "trakt/<user>/history"
        COLLECTION_SHOWS = "trakt/<user>/collection/shows"
        USER_PROFILE = "trakt/<user>/profile"
        USER_SETTINGS = "trakt/<user>/settings"
        USER_STATS = "trakt/<user>/stats"
        USER_WATCHING = "trakt/<user>/watching"
        USER_COLLECTION_SHOWS = "trakt/<user>/collection/shows"
        USER_WATCHED_SHOWS = "trakt/<user>/watched/shows"
        USER_HISTORY_SHOWS = "trakt/<user>/history/shows"
        HIDDEN_CALENDAR = "trakt/<user>/hidden/calendar"
        CALENDAR_SHOWS = "trakt/<user>/calendar/shows"
        CALENDAR_NEW_SHOWS = "trakt/<user>/calendar/shows/new"
        CALENDAR_PREMIERES = "trakt/<user>/calendar/shows/premieres"
        CALENDAR_MOVIES = "trakt/<user>/calendar/movies"
        PROGRESS_WATCHED = "trakt/<user>/progress/watched"
        PROGRESS_COLLECTED = "trakt/<user>/progress/collected"
        RECOMMENDATIONS_SHOWS = "trakt/<user>/recommendations/shows"
        RECOMMENDATIONS_MOVIES = "trakt/<user>/recommendations/movies"

    class tautulli:
        WATCH_HISTORY = "tautulli/<instance>/history/watch"
        TRANSCODE_HISTORY = "tautulli/<instance>/transcode/history"
        SERIES_TRACKED = "tautulli/<instance>/movies/tracked"
        EPISODES_TRENDS = "tautulli/<instance>/episodes/trends"
        DEVICES_USAGE_WEEKLY = "tautulli/<instance>/devices/usage/weekly"
        DEVICES_TRANSCODE_ANALYSIS = "tautulli/<instance>/devices/transcode/analysis"
        DEVICES_PLATFORM_USAGE_SUMMARY = "tautulli/<instance>/devices/usage/platform_summary"
        EPISODES_STATS_COMPLETION = "tautulli/<instance>/episodes/stats/completion"
        METADATA_INDEX = "tautulli/<instance>/metadata/index"
        USER_PATTERNS_VIEWING = "tautulli/<user>/patterns/viewing"
        USER_PATTERNS_BINGE = "tautulli/<user>/patterns/binge"
        USER_PATTERNS_TIME = "tautulli/<user>/patterns/time"
        USER_PROFILES_QUALITY = "tautulli/<user>/profiles/quality"
        USER_GENRES_AFFINITY = "tautulli/<user>/genres/affinity"
        USER_STATS_DROPOFFS = "tautulli/<user>/stats/dropoffs"
        TAUTULLI_SYNC_VIEWED = "sonarr/<instance>/sync/tautulli_viewed"
        TAUTULLI_SYNC_TRACKED = "sonarr/<instance>/sync/tautulli_tracked"
        TAUTULLI_SYNC_REWATCHES = "sonarr/<instance>/sync/tautulli_rewatches"
        TAUTULLI_SYNC_MISSING = "sonarr/<instance>/sync/tautulli_missing"
        TAUTULLI_SYNC_UPDATES = "sonarr/<instance>/sync/tautulli_updates"

    class machine_learning:
        TRANSCODE_FORMATS = "ml/transcode/formats"
        TRENDS_EPISODES = "ml/trends/episodes"
        VIEWING_USERS = "ml/viewing/users"
        PROFILES_QUALITY = "ml/profiles/quality"
